// This file will be auto-generated by: npx supabase gen types typescript --project-id=your-project-id > lib/supabase/types.ts
// For now, using placeholder types

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      families: {
        Row: {
          id: string;
          name: string;
          join_code: string | null;
          settings: Json;
          subscription_tier: string;
          subscription_expires_at: string | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          name: string;
          join_code?: string | null;
          settings?: Json;
          subscription_tier?: string;
          subscription_expires_at?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          name?: string;
          join_code?: string | null;
          settings?: Json;
          subscription_tier?: string;
          subscription_expires_at?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
      };
      users: {
        Row: {
          id: string;
          family_id: string;
          email: string;
          full_name: string | null;
          role: string;
          avatar_url: string | null;
          settings: Json;
          last_active_at: string | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id: string;
          family_id: string;
          email: string;
          full_name?: string | null;
          role?: string;
          avatar_url?: string | null;
          settings?: Json;
          last_active_at?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          family_id?: string;
          email?: string;
          full_name?: string | null;
          role?: string;
          avatar_url?: string | null;
          settings?: Json;
          last_active_at?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
      };
      children: {
        Row: {
          id: string;
          family_id: string;
          name: string;
          age_group: string;
          birthdate: string | null;
          birth_year: number | null;
          avatar_url: string | null;
          pin_code: string | null;
          points_balance: number;
          points_lifetime_earned: number;
          trust_level: number;
          trust_streak_days: number;
          settings: Json;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          family_id: string;
          name: string;
          age_group: string;
          birthdate?: string | null;
          birth_year?: number | null;
          avatar_url?: string | null;
          pin_code?: string | null;
          points_balance?: number;
          points_lifetime_earned?: number;
          trust_level?: number;
          trust_streak_days?: number;
          settings?: Json;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          family_id?: string;
          name?: string;
          age_group?: string;
          birthdate?: string | null;
          birth_year?: number | null;
          avatar_url?: string | null;
          pin_code?: string | null;
          points_balance?: number;
          points_lifetime_earned?: number;
          trust_level?: number;
          trust_streak_days?: number;
          settings?: Json;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
      };
      family_invitations: {
        Row: {
          id: string;
          family_id: string;
          invited_by: string;
          invited_email: string;
          token: string;
          status: string;
          expires_at: string;
          created_at: string;
          accepted_at: string | null;
        };
        Insert: {
          id?: string;
          family_id: string;
          invited_by: string;
          invited_email: string;
          token: string;
          status?: string;
          expires_at: string;
          created_at?: string;
          accepted_at?: string | null;
        };
        Update: {
          id?: string;
          family_id?: string;
          invited_by?: string;
          invited_email?: string;
          token?: string;
          status?: string;
          expires_at?: string;
          created_at?: string;
          accepted_at?: string | null;
        };
      };
      // Add more tables as needed...
    };
    Views: {
      v_child_today_tasks: {
        Row: {
          id: string;
          child_id: string;
          task_id: string;
          name: string;
          description: string | null;
          points: number;
          category: string;
          icon: string | null;
          frequency: string;
          approval_type: string;
          is_active: boolean;
          family_id: string;
          status: string | null;
          completed_at: string | null;
          completion_id: string | null;
        };
      };
      [key: string]: {
        Row: Record<string, unknown>;
      };
    };
    Functions: {
      add_points: {
        Args: {
          p_child_id: string;
          p_amount: number;
          p_type: string;
          p_reference_type?: string;
          p_reference_id?: string;
          p_description?: string;
        };
        Returns: number;
      };
      // Add more functions as needed...
    };
    Enums: {
      [_ in never]: never;
    };
  };
}
